better handling of LD_LIBRARY_PATH requirement
Affectiva/python-sdk-samples pull request #23
Opened 2020-10-08 19:36 UTC by adennie

Add note to readme.md file explaining that LD_LIBRARY_PATH must be set

Add a check at the top of the python sample to confirm that LD_LIBRARY_PATH is set to a valid location.

fixes SDK-3800

2020-10-08 19:45 UTC, umangmehta12 requested changes
Just a few points to think

2020-10-08 19:45 UTC, umangmehta12 commented on README.md
> +        export LD_LIBRARY_PATH=<python root>/lib/<python version>/site-packages/affvisionpy/lib`.
Two suggestions here:
1. I don't think `/usr/local/` or `/usr` is <python root> and <python version> seems vague i.e someone could assume its 3.6 and not python3.6....I think an example here would help
2. It would be helpful if we could add a snippet here on how to find the path, since devs can install modules in .local directory or using venv or pyenv something like:
" If you don't know where the affvisionpy library is installed. Do the following:
1. Open up the python shell
2. import affvisionpy as af
3. af.__file__ will show you where you installed the affvisionpy package and the lib directory is at the same level"

2020-10-08 19:45 UTC, umangmehta12 commented on affvisionpy_sample.py
> +if (not ld_library_path or not os.path.isfile(ld_library_path + "/libaffectiva-vision.so")):
Can we on the fly try to see if we can locate the affvisionpy module, if we can we could generate the LD_LIBRARY_PATH similar to the data dir else we should throw an error

2020-10-08 19:56 UTC, adennie commented on README.md
> +        export LD_LIBRARY_PATH=<python root>/lib/<python version>/site-packages/affvisionpy/lib`.
for (1) I'll update the example for the /usr/lib scenario.  People using pyenv or venv will have to adjust accordingly.
for (2) that won't work -- the whole problem is that you can't import affvisionpy unless you set LD_LIBRARY_PATH first.

2020-10-08 19:57 UTC, adennie commented on affvisionpy_sample.py
> +if (not ld_library_path or not os.path.isfile(ld_library_path + "/libaffectiva-vision.so")):
it's too late to set LD_LIBRARY_PATH inside the script, it needs to be set in advance.

2020-10-08 20:22 UTC, umangmehta12 commented on README.md
> +        export LD_LIBRARY_PATH=<python root>/lib/<python version>/site-packages/affvisionpy/lib`.
I might be wrong but, I think last time I did this with the revised packaging it worked, since we have rpath links to vision-library and tensorflow/ tflite...the problem arises when we try to process a frame when identification was enabled so maybe (2) would be possible.

2020-10-08 20:52 UTC, adennie commented on README.md
> +        export LD_LIBRARY_PATH=<python root>/lib/<python version>/site-packages/affvisionpy/lib`.
Your right, we should be able to import successfully; it won't fail until later when identity is enabled.  So I could move the check to where the `--identity` command line option is handled.  We still can't set LD_LIBRARY_PATH for the user, but at that point we can tell them what to set it to.

2020-10-08 22:24 UTC, umangmehta12 commented on README.md
> +        export LD_LIBRARY_PATH=<python root>/lib/<python version>/site-packages/affvisionpy/lib`.
okay, but I think we should have (2) be added to README to devs can figure out where the module is installed

2020-10-08 22:26 UTC, umangmehta12 requested changes

2020-10-08 22:26 UTC, umangmehta12 commented on affvisionpy_sample.py
> +if (not ld_library_path or not os.path.isfile(ld_library_path + "/libaffectiva-vision.so")):
I would maybe for convenience sake, set the LD_LIBRARY_PATH before the import of the affvisionpy module and check if the libraries are present at the path we expect them to be so that the users don't have to export them....we can meet to resolve this

2020-10-09 13:18 UTC, adennie commented on affvisionpy_sample.py
> +if (not ld_library_path or not os.path.isfile(ld_library_path + "/libaffectiva-vision.so")):
it does no good to set LD_LIBRARY_PATH inside the script, it needs to be done externally, before the script is run.

2020-10-12 18:18 UTC, adennie commented on README.md
> +        export LD_LIBRARY_PATH=<python root>/lib/<python version>/site-packages/affvisionpy/lib`.
@umangmehta12 I updated the README to show how to determine the module installation path and set the LD_LIBRARY_PATH based on that.

2020-10-12 18:27 UTC, umangmehta12 approved these changes
Looks good to me, thanks for the investigation and clean-up

2020-10-19 20:53 UTC, merged