SDK-3677 | Change face bounding box's opacity
Affectiva/python-sdk-samples pull request #35
Opened 2021-03-24 12:25 UTC by ahmedalmoraly

2021-06-01 13:36 UTC, adennie requested changes

2021-06-01 13:36 UTC, adennie commented on display_metrics.py
> +        joy_value = emotions[Emotion.joy] if Emotion.joy in emotions else 0
The purpose of the logic below that sets the color based on particular metrics and a threshold is not self-evident.  Could you add an explanatory comment?

2021-06-07 20:39 UTC, umangmehta12 commented on display_metrics.py
> +        joy_value = emotions[Emotion.joy] if Emotion.joy in emotions else 0
Discussed this with Ahmed during one of our calls. We would have the valence based visualizations mainly based on valence metrics wherein negative valence color i.e red should show up when the valence is < 0 and positive valence color i.e green should show up when valence is > 0

2021-06-08 18:57 UTC, umangmehta12 approved these changes
Looks good to me, thanks for the updates

2021-06-09 14:16 UTC, adennie commented on display_metrics.py
> +        norm_val = (val - self.red) / (self.green - self.red)
I was asking because I wasn't sure if we wanted a continuum of colors between red and green, or a more binary red/green visualization.  Either way is actually OK with me visually, but I just wanted to see what the intention was here.

2021-06-09 14:16 UTC, adennie approved these changes

2021-06-09 14:36 UTC, ahmedalmoraly commented on display_metrics.py
> +        norm_val = (val - self.red) / (self.green - self.red)
yes. valence of 0 would produce norm_val of 0.5 (middle of the range) so it would be a brownish green color. positive valence would result in higher norm values, which would produce greener color, and vice verse; negative valence result in lower norm values that produce red-er color.

2021-06-09 14:36 UTC, merged